### PR TITLE
set resource requests equal to limits to avoid OOM

### PR DESCRIPTION
**Pull request by bitscuit**
might need to consider whether it is possible to reduce the required resources, but that should be a separate issue

### CODE REVIEW

**Comment by cheewaio** [comment]
@bitscuit I'm a bit concerned that now doubling the resource usage. Other than supporting CLI downloads, I am not sure what else might be requiring more memory. Rather than creating a separate PR, I think we should  do a bit of research to justify the settings, if we need to keep them different or increase the limits. Thanks
https://access.redhat.com/solutions/3170981

**Comment by bitscuit** [comment]
The resource usage has not doubled. The limit hasn't been changed, so it could have always used up to that much CPU/memory. The main issue here is because resource requests went up, Kubernetes has to guarantee that much resource is available to the pod, so there might be scheduling problems. But if the hardware requirements in the [Knowledge Centre docs](https://www.ibm.com/support/knowledgecenter/SSHKN6/installer/1.1.0/hardware_sizing_reqs.html) are accurate, then it should be fine in the short term

**Comment by cheewaio** [comment]
I see. That means will require more minimum hardware resources right? 
BTW, I don't see any entry for platform-api in the doc, we probably should have one.
I am OK if you want to go with 512Mib for now. But we should definitely open an issue to track the follow-up actions needed. Thanks

**Pull request merged**
