### PR TITLE
updates to fix case bundle linting issues

### PR DESCRIPTION
**Pull request by bitscuit**

### CODE REVIEW

**Comment by cheewaio** [comment]
Does management ingress supporting the new ingress?

**Comment by bitscuit** [comment]
Tested fresh install and upgrade scenarios, and ingress is working. Even when using `extensions/v1beta` for the Ingress, OCP was changing it to `networking.k8s.io/v1beta1`.

**Comment by cheewaio** [comment]
good thanks. let me know when it's ready to merge

**Comment by bitscuit** [comment]
ready to be merged

**Review by cheewaio — APPROVED** [review]
/lgtm

**Pull request merged**
